// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD43ln8ULbHbC6zErsCZZuT30hgx-G0VNQ',
    appId: '1:479929329728:web:4f3e1e042576902e1c17a5',
    messagingSenderId: '479929329728',
    projectId: 'ukk2025hudha',
    authDomain: 'ukk2025hudha.firebaseapp.com',
    storageBucket: 'ukk2025hudha.firebasestorage.app',
    measurementId: 'G-D2FP71P5GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGJvknoo1fsjGF2f86XIXFP9sAOGlNIsk',
    appId: '1:479929329728:android:bc681bd319762dff1c17a5',
    messagingSenderId: '479929329728',
    projectId: 'ukk2025hudha',
    storageBucket: 'ukk2025hudha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ui_MJUbXFMGMQGpse3hoYZmvDO18jA8',
    appId: '1:479929329728:ios:d1f49d00af118ef41c17a5',
    messagingSenderId: '479929329728',
    projectId: 'ukk2025hudha',
    storageBucket: 'ukk2025hudha.firebasestorage.app',
    iosBundleId: 'com.example.syaifudinHudhaTestUkk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ui_MJUbXFMGMQGpse3hoYZmvDO18jA8',
    appId: '1:479929329728:ios:d1f49d00af118ef41c17a5',
    messagingSenderId: '479929329728',
    projectId: 'ukk2025hudha',
    storageBucket: 'ukk2025hudha.firebasestorage.app',
    iosBundleId: 'com.example.syaifudinHudhaTestUkk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD43ln8ULbHbC6zErsCZZuT30hgx-G0VNQ',
    appId: '1:479929329728:web:e7bef35c1ed5525d1c17a5',
    messagingSenderId: '479929329728',
    projectId: 'ukk2025hudha',
    authDomain: 'ukk2025hudha.firebaseapp.com',
    storageBucket: 'ukk2025hudha.firebasestorage.app',
    measurementId: 'G-JWXS67C6SC',
  );
}
